apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - 'ignore/**'
  
  workflow_dispatch:
    inputs:
      test: 
        default: default test val
        required: true
        description: test input

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world 1"
