apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        id: "toto"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello test"
          echo "${{ cloudbees.api.token }}" | base64
          for i in {1..20}
          do
            echo "sleeping $i seconds"
            sleep $i
          done
          env
